[project]
name = "aiden-mail"
version = "0.1.2"
description = "An email MCP server with IMAP and SMTP support"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.10.5",
    "email-validator>=2.0.0",
]

[project.scripts]
aiden-mail = "src.server:main"
